# Generated by Django 6.0.3 on 2026-03-23 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
            ],
            options={
                'db_table': '"jose_gabriel"."veiculo"',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"jose_gabriel"."usuario"',
            },
        ),
        migrations.CreateModel(
            name='Caminhao',
            fields=[
                ('veiculo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.veiculo')),
                ('quantidade_eixos', models.IntegerField()),
                ('capacidade_toneladas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_carroceria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"jose_gabriel"."caminhao"',
            },
            bases=('core.veiculo',),
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('veiculo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.veiculo')),
                ('ar_condicionado', models.BooleanField(default=False)),
                ('numero_portas', models.IntegerField()),
                ('tipo_combustivel', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"jose_gabriel"."carro"',
            },
            bases=('core.veiculo',),
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('veiculo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.veiculo')),
                ('refrigeracao', models.CharField(max_length=50)),
                ('tipo_partida', models.CharField(max_length=50)),
                ('cilindradas', models.IntegerField()),
            ],
            options={
                'db_table': '"jose_gabriel"."moto"',
            },
            bases=('core.veiculo',),
        ),
        migrations.CreateModel(
            name='Triciclo',
            fields=[
                ('veiculo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.veiculo')),
                ('tipo_tracao', models.CharField(max_length=50)),
                ('capacidade_carga', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': '"jose_gabriel"."triciclo"',
            },
            bases=('core.veiculo',),
        ),
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_revisao', models.DateField()),
                ('quilometragem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('responsavel', models.CharField(max_length=100)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='core.veiculo')),
            ],
            options={
                'db_table': '"jose_gabriel"."revisao"',
            },
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='core.usuario'),
        ),
    ]
